import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/homeone">HomeOne</Link>
        </li>
        <li>
          <Link to="/detailbuilding">DetailBuilding</Link>
        </li>
        <li>
          <Link to="/draftselectedweb">Draftselectedweb</Link>
        </li>
        <li>
          <Link to="/draftgridweb">Draftgridweb</Link>
        </li>
        <li>
          <Link to="/auksjon">Auksjon</Link>
        </li>
        <li>
          <Link to="/auksjononclikk">AuksjonOnclikk</Link>
        </li>
        <li>
          <Link to="/lightpointofsaledashboard">LightPointofSaleDashboard</Link>
        </li>
        <li>
          <Link to="/lightpointofsaleanalytics">LightPointofSaleAnalytics</Link>
        </li>
        <li>
          <Link to="/lightpointofsalecustomers">LightPointofSaleCustomers</Link>
        </li>
        <li>
          <Link to="/lightpointofsaleproducts">LightPointofSaleProducts</Link>
        </li>
        <li>
          <Link to="/finnauksjon">Finnauksjon</Link>
        </li>
        <li>
          <Link to="/lightpointofsaleeditproduct">
            LightPointofSaleEditProduct
          </Link>
        </li>
        <li>
          <Link to="/lightpointofsalecoupons">LightPointofSaleCoupons</Link>
        </li>
        <li>
          <Link to="/lightpointofsaleemployeeshift">
            LightPointofSaleEmployeeShift
          </Link>
        </li>
        <li>
          <Link to="/lightpointofsalesettings">LightPointofSaleSettings</Link>
        </li>
        <li>
          <Link to="/categoryweb">Categoryweb</Link>
        </li>
        <li>
          <Link to="/addweb">Addweb</Link>
        </li>
        <li>
          <Link to="/darkprofile">DarkProfile</Link>
        </li>
        <li>
          <Link to="/darkchats">DarkChats</Link>
        </li>
        <li>
          <Link to="/darkcontacts">DarkContacts</Link>
        </li>
        <li>
          <Link to="/darkcalls">DarkCalls</Link>
        </li>
        <li>
          <Link to="/ordersweb">Ordersweb</Link>
        </li>
        <li>
          <Link to="/orderskanbanweb">Orderskanbanweb</Link>
        </li>
        <li>
          <Link to="/darkbookmark">DarkBookmark</Link>
        </li>
        <li>
          <Link to="/darksettings">DarkSettings</Link>
        </li>
        <li>
          <Link to="/jobfindertwo">JobFinderTwo</Link>
        </li>
        <li>
          <Link to="/realestateone">RealEstateOne</Link>
        </li>
        <li>
          <Link to="/livesaleswhatnot">LiveSaleswhatnot</Link>
        </li>
        <li>
          <Link to="/admindashboard">AdminDashboard</Link>
        </li>
        <li>
          <Link to="/property">Property</Link>
        </li>
        <li>
          <Link to="/taskdashboard">TaskDashboard</Link>
        </li>
        <li>
          <Link to="/dashboarddarkmode">DashboardDarkmode</Link>
        </li>
        <li>
          <Link to="/overview">Overview</Link>
        </li>
        <li>
          <Link to="/weather">Weather</Link>
        </li>
        <li>
          <Link to="/realestatedashboard">RealEstateDashboard</Link>
        </li>
        <li>
          <Link to="/overviewone">OverviewOne</Link>
        </li>
        <li>
          <Link to="/propertyone">PropertyOne</Link>
        </li>
        <li>
          <Link to="/nftdark">NFTDark</Link>
        </li>
        <li>
          <Link to="/dashboardone">DashboardOne</Link>
        </li>
        <li>
          <Link to="/onlinetaxidashboard">OnlineTaxiDashboard</Link>
        </li>
        <li>
          <Link to="/dashboardthree">DashboardThree</Link>
        </li>
        <li>
          <Link to="/realestate">RealEstate</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/homepagevone">HomepageVOne</Link>
        </li>
        <li>
          <Link to="/leieinn">LeieInn</Link>
        </li>
        <li>
          <Link to="/discover">Discover</Link>
        </li>
        <li>
          <Link to="/browse">Browse</Link>
        </li>
        <li>
          <Link to="/playlist">Playlist</Link>
        </li>
        <li>
          <Link to="/charts">Charts</Link>
        </li>
        <li>
          <Link to="/musicplay">MusicPlay</Link>
        </li>
        <li>
          <Link to="/frammallsbuy">FraMmallsBuy</Link>
        </li>
        <li>
          <Link to="/finnhotel">FinnHotel</Link>
        </li>
        <li>
          <Link to="/ipadminieight">IPadminiEight</Link>
        </li>
        <li>
          <Link to="/ipadminieleven">IPadminiEleven</Link>
        </li>
        <li>
          <Link to="/ipadminiten">IPadminiTen</Link>
        </li>
        <li>
          <Link to="/homedark">HomeDark</Link>
        </li>
        <li>
          <Link to="/citytempone">CityTempOne</Link>
        </li>
        <li>
          <Link to="/citytemp">CityTemp</Link>
        </li>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/analytics">Analytics</Link>
        </li>
        <li>
          <Link to="/formaddnewcampaign">FormAddNewCampaign</Link>
        </li>
        <li>
          <Link to="/dashboard1">Dashboard1</Link>
        </li>
        <li>
          <Link to="/adscampaignlist">AdsCampaignList</Link>
        </li>
        <li>
          <Link to="/socialnetworkcampaignlist">SocialNetworkCampaignList</Link>
        </li>
        <li>
          <Link to="/spendinglisttable">SpendingListTable</Link>
        </li>
        <li>
          <Link to="/jobfinder">JobFinder</Link>
        </li>
        <li>
          <Link to="/dashboarddarkmodeone">DashboardDarkmodeOne</Link>
        </li>
        <li>
          <Link to="/jobfinderone">JobfinderOne</Link>
        </li>
        <li>
          <Link to="/macbookprotwo">MacBookProTwo</Link>
        </li>
        <li>
          <Link to="/sewujobjobfinderdashboard">SewuJobJobFinderDashboard</Link>
        </li>
        <li>
          <Link to="/dekstoptwo">DekstopTwo</Link>
        </li>
        <li>
          <Link to="/foodplandashboard">FoodPlanDashboard</Link>
        </li>
        <li>
          <Link to="/onlinecoursesearchpage">OnlineCourseSearchpage</Link>
        </li>
        <li>
          <Link to="/dekstopone">DekstopOne</Link>
        </li>
        <li>
          <Link to="/eventdashboard">EventDashboard</Link>
        </li>
        <li>
          <Link to="/propertydashboard">PropertyDashboard</Link>
        </li>
        <li>
          <Link to="/ultimatecoursedashboard">UltimateCourseDashboard</Link>
        </li>
        <li>
          <Link to="/dashboardchat">Dashboardchat</Link>
        </li>
        <li>
          <Link to="/dekstop">Dekstop</Link>
        </li>
        <li>
          <Link to="/nofonftmarketplacedashboard">
            NOFONFTMarketplaceDashboard
          </Link>
        </li>
        <li>
          <Link to="/videoanalysis">VideoAnalysis</Link>
        </li>
        <li>
          <Link to="/dashboard2">Dashboard2</Link>
        </li>
        <li>
          <Link to="/aucaaudiobookdashboard">AucaAudioBookDashboard</Link>
        </li>
        <li>
          <Link to="/singlephotoone">SinglePhotoOne</Link>
        </li>
        <li>
          <Link to="/userprofile">UserProfile</Link>
        </li>
        <li>
          <Link to="/searchresults">SearchResults</Link>
        </li>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/videochat">VideoChat</Link>
        </li>
        <li>
          <Link to="/directmessage">DirectMessage</Link>
        </li>
        <li>
          <Link to="/settingstwo">SettingsTwo</Link>
        </li>
        <li>
          <Link to="/myfriends">MyFriends</Link>
        </li>
        <li>
          <Link to="/passwordrecovery">PasswordRecovery</Link>
        </li>
        <li>
          <Link to="/videofullscreen">VideoFullScreen</Link>
        </li>
        <li>
          <Link to="/singlestory">SingleStory</Link>
        </li>
        <li>
          <Link to="/notifications">Notifications</Link>
        </li>
        <li>
          <Link to="/events">Events</Link>
        </li>
        <li>
          <Link to="/singlevideo">SingleVideo</Link>
        </li>
        <li>
          <Link to="/gallery">Gallery</Link>
        </li>
        <li>
          <Link to="/myprofile">MyProfile</Link>
        </li>
        <li>
          <Link to="/stories">Stories</Link>
        </li>
        <li>
          <Link to="/messages">Messages</Link>
        </li>
        <li>
          <Link to="/singlepost">SinglePost</Link>
        </li>
        <li>
          <Link to="/singleevent">SingleEvent</Link>
        </li>
        <li>
          <Link to="/groupmessage">GroupMessage</Link>
        </li>
        <li>
          <Link to="/singlephoto">SinglePhoto</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/homepagevtwo">HomepageVTwo</Link>
        </li>
        <li>
          <Link to="/productlist">ProductList</Link>
        </li>
        <li>
          <Link to="/completed">Completed</Link>
        </li>
        <li>
          <Link to="/homepagevthree">HomepageVThree</Link>
        </li>
        <li>
          <Link to="/productdetails">ProductDetails</Link>
        </li>
        <li>
          <Link to="/categorieswithsidebar">CategorieswithSidebar</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/onlywebsite">Onlywebsite</Link>
        </li>
        <li>
          <Link to="/history">History</Link>
        </li>
        <li>
          <Link to="/aktivitet">Aktivitet</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/landingalt">LandingAlt</Link>
        </li>
        <li>
          <Link to="/companydetail">CompanyDetail</Link>
        </li>
        <li>
          <Link to="/ownerpreview">Ownerpreview</Link>
        </li>
        <li>
          <Link to="/creatoronclick">CreatorOnclick</Link>
        </li>
        <li>
          <Link to="/activebid">ActiveBid</Link>
        </li>
        <li>
          <Link to="/market">Market</Link>
        </li>
        <li>
          <Link to="/dashboardtwo">DashboardTwo</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/myprofilecollection">MyProfileCollection</Link>
        </li>
        <li>
          <Link to="/marketdetail">MarketDetail</Link>
        </li>
        <li>
          <Link to="/myprofilehistory">MyProfileHistory</Link>
        </li>
        <li>
          <Link to="/otheruserprofile">OtherUserProfile</Link>
        </li>
        <li>
          <Link to="/saved">Saved</Link>
        </li>
        <li>
          <Link to="/message">Message</Link>
        </li>
        <li>
          <Link to="/myprofilepreview">MyProfilePreview</Link>
        </li>
        <li>
          <Link to="/myprofilewallet">MyProfileWallet</Link>
        </li>
        <li>
          <Link to="/messageone">MessageOne</Link>
        </li>
        <li>
          <Link to="/top10netflixcombyhtmltodesignfreeversion18two">
            Top10netflixcombyhtmltodesignFREEversion18Two
          </Link>
        </li>
        <li>
          <Link to="/htmltode">Htmltode</Link>
        </li>
        <li>
          <Link to="/wwwmsncombyhtmltodesignfreeversion19022023">
            WwwmsncombyhtmltodesignFREEversion19022023
          </Link>
        </li>
        <li>
          <Link to="/notionformsiobyhtmltodesignfreeversion1902twenty">
            NotionformsiobyhtmltodesignFREEversion1902Twenty
          </Link>
        </li>
        <li>
          <Link to="/wwwslottsfjellnobyhtmltodesignfreeversion18zerotwo">
            WwwslottsfjellnobyhtmltodesignFREEversion18ZeroTwo
          </Link>
        </li>
        <li>
          <Link to="/wwwnetflixcombyhtmltodesignfreeversion1802two">
            WwwnetflixcombyhtmltodesignFREEversion1802Two
          </Link>
        </li>
        <li>
          <Link to="/wwwslottsfjellnobyhtmltodesignfreeversion18zeroone">
            WwwslottsfjellnobyhtmltodesignFREEversion18ZeroOne
          </Link>
        </li>
        <li>
          <Link to="/div">Div</Link>
        </li>
        <li>
          <Link to="/homepage2dark">Homepage2Dark</Link>
        </li>
        <li>
          <Link to="/desktoptwo">DesktopTwo</Link>
        </li>
        <li>
          <Link to="/wwwslottsfjellnobyhtmltodesignfreeversion18zero">
            WwwslottsfjellnobyhtmltodesignFREEversion18Zero
          </Link>
        </li>
        <li>
          <Link to="/raw">Raw</Link>
        </li>
        <li>
          <Link to="/wwwgrundervekstnobyhtmltodesignfreeversion18">
            WwwgrundervekstnobyhtmltodesignFREEversion18
          </Link>
        </li>
        <li>
          <Link to="/reditedraw">Reditedraw</Link>
        </li>
        <li>
          <Link to="/httpslatinaspycomstories">Httpslatinaspycomstories</Link>
        </li>
        <li>
          <Link to="/pr">Pr</Link>
        </li>
        <li>
          <Link to="/folkeinvestnobyhtmltodesignfreeversion1802twenty">
            FolkeinvestnobyhtmltodesignFREEversion1802Twenty
          </Link>
        </li>
        <li>
          <Link to="/divpage">Divpage</Link>
        </li>
        <li>
          <Link to="/divone">DivOne</Link>
        </li>
        <li>
          <Link to="/edited">Edited</Link>
        </li>
        <li>
          <Link to="/lando">Lando</Link>
        </li>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/faphousecombyhtmltodesignfreeversion03032023">
            FaphousecombyhtmltodesignFREEversion03032023
          </Link>
        </li>
        <li>
          <Link to="/wwwnetflixcombyhtmltodesignfreeversion0203two">
            WwwnetflixcombyhtmltodesignFREEversion0203Two
          </Link>
        </li>
        <li>
          <Link to="/option">Option</Link>
        </li>
        <li>
          <Link to="/theporndudecombyhtmltodesignfreeversion0303two">
            TheporndudecombyhtmltodesignFREEversion0303Two
          </Link>
        </li>
        <li>
          <Link to="/wwwbokklubbennobyhtmltodesignfreeversion04three">
            WwwbokklubbennobyhtmltodesignFREEversion04Three
          </Link>
        </li>
        <li>
          <Link to="/opt">Opt</Link>
        </li>
        <li>
          <Link to="/wwwzolacombyhtmltodesignfreeversion01032023">
            WwwzolacombyhtmltodesignFREEversion01032023
          </Link>
        </li>
        <li>
          <Link to="/placeitnetbyhtmltodesignfreeversion21022023">
            PlaceitnetbyhtmltodesignFREEversion21022023
          </Link>
        </li>
        <li>
          <Link to="/getdoordashcombyhtmltodesignfreeversion0103">
            GetdoordashcombyhtmltodesignFREEversion0103
          </Link>
        </li>
        <li>
          <Link to="/land">Land</Link>
        </li>
        <li>
          <Link to="/landone">LandOne</Link>
        </li>
        <li>
          <Link to="/placeitnetbyhtmltodesignfreeversion21022023one">
            PlaceitnetbyhtmltodesignFREEversion21022023One
          </Link>
        </li>
        <li>
          <Link to="/landthree">LandThree</Link>
        </li>
        <li>
          <Link to="/ladone">LadOne</Link>
        </li>
        <li>
          <Link to="/footer">Footer</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
